//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuiltDifferentMobileApp.Ressource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuiltDifferentMobileApp.Ressource.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AddWorkoutPageDescription {
            get {
                return ResourceManager.GetString("AddWorkoutPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (minutes).
        /// </summary>
        public static string AddWorkoutPageDuration {
            get {
                return ResourceManager.GetString("AddWorkoutPageDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reps.
        /// </summary>
        public static string AddWorkoutPageReps {
            get {
                return ResourceManager.GetString("AddWorkoutPageReps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest Time (seconds).
        /// </summary>
        public static string AddWorkoutPageRestTime {
            get {
                return ResourceManager.GetString("AddWorkoutPageRestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Workout.
        /// </summary>
        public static string AddWorkoutPageTitle {
            get {
                return ResourceManager.GetString("AddWorkoutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout Type.
        /// </summary>
        public static string AddWorkoutPageType {
            get {
                return ResourceManager.GetString("AddWorkoutPageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube Video Link.
        /// </summary>
        public static string AddWorkoutPageVideoLink {
            get {
                return ResourceManager.GetString("AddWorkoutPageVideoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise Name.
        /// </summary>
        public static string AddWorkoutPageWorkoutName {
            get {
                return ResourceManager.GetString("AddWorkoutPageWorkoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        public static string AddWorkoutPageWorkoutSets {
            get {
                return ResourceManager.GetString("AddWorkoutPageWorkoutSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   , .
        /// </summary>
        public static string AdminCoachApprovalGender {
            get {
                return ResourceManager.GetString("AdminCoachApprovalGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coach Application.
        /// </summary>
        public static string AdminCoachApprovalProfileTitle {
            get {
                return ResourceManager.GetString("AdminCoachApprovalProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string AdminCoachApprovalRequests {
            get {
                return ResourceManager.GetString("AdminCoachApprovalRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Coaches.
        /// </summary>
        public static string AdminCoachApprovalTitle {
            get {
                return ResourceManager.GetString("AdminCoachApprovalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pending coach requests.
        /// </summary>
        public static string AdminCoachNoPendingCoaches {
            get {
                return ResourceManager.GetString("AdminCoachNoPendingCoaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to be a coach.
        /// </summary>
        public static string ApplyToBeACoach {
            get {
                return ResourceManager.GetString("ApplyToBeACoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available for new clients?.
        /// </summary>
        public static string AvailabilityLabel {
            get {
                return ResourceManager.GetString("AvailabilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        public static string CoachAddMealCaloriesLabel {
            get {
                return ResourceManager.GetString("CoachAddMealCaloriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbs.
        /// </summary>
        public static string CoachAddMealCarbsLabel {
            get {
                return ResourceManager.GetString("CoachAddMealCarbsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat.
        /// </summary>
        public static string CoachAddMealFatLabel {
            get {
                return ResourceManager.GetString("CoachAddMealFatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste an image link here.
        /// </summary>
        public static string CoachAddMealImageLabel {
            get {
                return ResourceManager.GetString("CoachAddMealImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Name.
        /// </summary>
        public static string CoachAddMealNameLabel {
            get {
                return ResourceManager.GetString("CoachAddMealNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein.
        /// </summary>
        public static string CoachAddMealProteinLabel {
            get {
                return ResourceManager.GetString("CoachAddMealProteinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the ingredients and cook time..
        /// </summary>
        public static string CoachAddMealRecipeLabel {
            get {
                return ResourceManager.GetString("CoachAddMealRecipeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Meal.
        /// </summary>
        public static string CoachAddMealTitle {
            get {
                return ResourceManager.GetString("CoachAddMealTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Type.
        /// </summary>
        public static string CoachAddMealTypeLabel {
            get {
                return ResourceManager.GetString("CoachAddMealTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string CoachDashboardBoard {
            get {
                return ResourceManager.GetString("CoachDashboardBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CoachDashboardClientName {
            get {
                return ResourceManager.GetString("CoachDashboardClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Progress.
        /// </summary>
        public static string CoachDashboardClientProgress {
            get {
                return ResourceManager.GetString("CoachDashboardClientProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of clients.
        /// </summary>
        public static string CoachDashboardNumOfClient {
            get {
                return ResourceManager.GetString("CoachDashboardNumOfClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search clients.
        /// </summary>
        public static string CoachDashboardSearchClients {
            get {
                return ResourceManager.GetString("CoachDashboardSearchClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string CoachDashboardTitle {
            get {
                return ResourceManager.GetString("CoachDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Clients.
        /// </summary>
        public static string CoachDashboardYourClients {
            get {
                return ResourceManager.GetString("CoachDashboardYourClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string CoachMealsClientPlanAdd {
            get {
                return ResourceManager.GetString("CoachMealsClientPlanAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Plan.
        /// </summary>
        public static string CoachMealsClientPlanTitle {
            get {
                return ResourceManager.GetString("CoachMealsClientPlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string CoachMealsEdit {
            get {
                return ResourceManager.GetString("CoachMealsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meals.
        /// </summary>
        public static string CoachMealsTitle {
            get {
                return ResourceManager.GetString("CoachMealsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Coach List.
        /// </summary>
        public static string CoachSelectionAvalibleListLabel {
            get {
                return ResourceManager.GetString("CoachSelectionAvalibleListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Coach was found corresponding to your search..
        /// </summary>
        public static string CoachSelectionNoAvalibleListLabel {
            get {
                return ResourceManager.GetString("CoachSelectionNoAvalibleListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  $/month.
        /// </summary>
        public static string CoachSelectionPriceLabel {
            get {
                return ResourceManager.GetString("CoachSelectionPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string CoachSelectionPriceTitleLabel {
            get {
                return ResourceManager.GetString("CoachSelectionPriceTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string CoachSelectionRequestButton {
            get {
                return ResourceManager.GetString("CoachSelectionRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Workout Plan.
        /// </summary>
        public static string CoachWorkoutClientPlanTitle {
            get {
                return ResourceManager.GetString("CoachWorkoutClientPlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workouts.
        /// </summary>
        public static string CoachWorkoutTitle {
            get {
                return ResourceManager.GetString("CoachWorkoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmedPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmedPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your coach and start your fitness journey as soon as possible!.
        /// </summary>
        public static string CriteriasTitleLabel {
            get {
                return ResourceManager.GetString("CriteriasTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Weight.
        /// </summary>
        public static string CurrentWeightLabel {
            get {
                return ResourceManager.GetString("CurrentWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string DontHaveAccountLabel {
            get {
                return ResourceManager.GetString("DontHaveAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Meal.
        /// </summary>
        public static string EditMealPageTitle {
            get {
                return ResourceManager.GetString("EditMealPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Workout.
        /// </summary>
        public static string EditWorkoutPageTitle {
            get {
                return ResourceManager.GetString("EditWorkoutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a gender, if you have a prefered coach gender.
        /// </summary>
        public static string FindACoachByCriteriaGenderLabel {
            get {
                return ResourceManager.GetString("FindACoachByCriteriaGenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us find one for you!.
        /// </summary>
        public static string FindACoachByCriteriaLabel {
            get {
                return ResourceManager.GetString("FindACoachByCriteriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coach Name.
        /// </summary>
        public static string FindACoachByCriteriaNameLabel {
            get {
                return ResourceManager.GetString("FindACoachByCriteriaNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - OR -.
        /// </summary>
        public static string FindACoachByCriteriaOrLabel {
            get {
                return ResourceManager.GetString("FindACoachByCriteriaOrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string FindACoachByCriteriaSearchButton {
            get {
                return ResourceManager.GetString("FindACoachByCriteriaSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the coaching type that best fits you.
        /// </summary>
        public static string FindACoachByCriteriaTypeLabel {
            get {
                return ResourceManager.GetString("FindACoachByCriteriaTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a coach by name.
        /// </summary>
        public static string FindACoachByNameLabel {
            get {
                return ResourceManager.GetString("FindACoachByNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password ?.
        /// </summary>
        public static string ForgotPasswordLabel {
            get {
                return ResourceManager.GetString("ForgotPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email associated with your account..
        /// </summary>
        public static string ForgotPasswordPrompt {
            get {
                return ResourceManager.GetString("ForgotPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullNamePlaceholder {
            get {
                return ResourceManager.GetString("FullNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string GenderLabel {
            get {
                return ResourceManager.GetString("GenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is verified.
        /// </summary>
        public static string IsVerifiedLabel {
            get {
                return ResourceManager.GetString("IsVerifiedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer meal coaching.
        /// </summary>
        public static string MealServiceLabel {
            get {
                return ResourceManager.GetString("MealServiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Profile.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUpLabel {
            get {
                return ResourceManager.GetString("SignUpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Weight.
        /// </summary>
        public static string StartWeightLabel {
            get {
                return ResourceManager.GetString("StartWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer workout coaching.
        /// </summary>
        public static string WorkoutServiceLabel {
            get {
                return ResourceManager.GetString("WorkoutServiceLabel", resourceCulture);
            }
        }
    }
}
