//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuiltDifferentMobileApp.Ressource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuiltDifferentMobileApp.Ressource.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account already exists for the email that you have entered..
        /// </summary>
        public static string AccountAlreadyExists {
            get {
                return ResourceManager.GetString("AccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you entered does not belong to an account. Please check your email and try again..
        /// </summary>
        public static string AccountNotFoundText {
            get {
                return ResourceManager.GetString("AccountNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Saved..
        /// </summary>
        public static string AddMealSavedTitle {
            get {
                return ResourceManager.GetString("AddMealSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        public static string AddMealViewModelBreakfast {
            get {
                return ResourceManager.GetString("AddMealViewModelBreakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        public static string AddMealViewModelDinner {
            get {
                return ResourceManager.GetString("AddMealViewModelDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        public static string AddMealViewModelLunch {
            get {
                return ResourceManager.GetString("AddMealViewModelLunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snack.
        /// </summary>
        public static string AddMealViewModelSnack {
            get {
                return ResourceManager.GetString("AddMealViewModelSnack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AddWorkoutPageDescription {
            get {
                return ResourceManager.GetString("AddWorkoutPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Duration (minutes).
        /// </summary>
        public static string AddWorkoutPageDuration {
            get {
                return ResourceManager.GetString("AddWorkoutPageDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Reps.
        /// </summary>
        public static string AddWorkoutPageReps {
            get {
                return ResourceManager.GetString("AddWorkoutPageReps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Rest Time (seconds).
        /// </summary>
        public static string AddWorkoutPageRestTime {
            get {
                return ResourceManager.GetString("AddWorkoutPageRestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Workout.
        /// </summary>
        public static string AddWorkoutPageTitle {
            get {
                return ResourceManager.GetString("AddWorkoutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout Type.
        /// </summary>
        public static string AddWorkoutPageType {
            get {
                return ResourceManager.GetString("AddWorkoutPageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube Video Link.
        /// </summary>
        public static string AddWorkoutPageVideoLink {
            get {
                return ResourceManager.GetString("AddWorkoutPageVideoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise Name.
        /// </summary>
        public static string AddWorkoutPageWorkoutName {
            get {
                return ResourceManager.GetString("AddWorkoutPageWorkoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sets.
        /// </summary>
        public static string AddWorkoutPageWorkoutSets {
            get {
                return ResourceManager.GetString("AddWorkoutPageWorkoutSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout Saved..
        /// </summary>
        public static string AddWorkoutSaved {
            get {
                return ResourceManager.GetString("AddWorkoutSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardio.
        /// </summary>
        public static string AddWorkoutTypeCardio {
            get {
                return ResourceManager.GetString("AddWorkoutTypeCardio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm Up.
        /// </summary>
        public static string AddWorkoutTypeWarmUp {
            get {
                return ResourceManager.GetString("AddWorkoutTypeWarmUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Training.
        /// </summary>
        public static string AddWorkoutTypeWeightTraining {
            get {
                return ResourceManager.GetString("AddWorkoutTypeWeightTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string AdminCoachApprovalApprove {
            get {
                return ResourceManager.GetString("AdminCoachApprovalApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string AdminCoachApprovalDeny {
            get {
                return ResourceManager.GetString("AdminCoachApprovalDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   , .
        /// </summary>
        public static string AdminCoachApprovalGender {
            get {
                return ResourceManager.GetString("AdminCoachApprovalGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning to previous page..
        /// </summary>
        public static string AdminCoachApprovalNoProfileMessage {
            get {
                return ResourceManager.GetString("AdminCoachApprovalNoProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load coach&apos;s profile!.
        /// </summary>
        public static string AdminCoachApprovalNoProfileTitle {
            get {
                return ResourceManager.GetString("AdminCoachApprovalNoProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans: .
        /// </summary>
        public static string AdminCoachApprovalPlansOfferedTitle {
            get {
                return ResourceManager.GetString("AdminCoachApprovalPlansOfferedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coach Application.
        /// </summary>
        public static string AdminCoachApprovalProfileTitle {
            get {
                return ResourceManager.GetString("AdminCoachApprovalProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string AdminCoachApprovalRequests {
            get {
                return ResourceManager.GetString("AdminCoachApprovalRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Coaches.
        /// </summary>
        public static string AdminCoachApprovalTitle {
            get {
                return ResourceManager.GetString("AdminCoachApprovalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pending coach requests.
        /// </summary>
        public static string AdminCoachNoPendingCoaches {
            get {
                return ResourceManager.GetString("AdminCoachNoPendingCoaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to be a coach.
        /// </summary>
        public static string ApplyToBeACoach {
            get {
                return ResourceManager.GetString("ApplyToBeACoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your application has been denied.
        /// </summary>
        public static string ApprovalDeniedBody {
            get {
                return ResourceManager.GetString("ApprovalDeniedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application has been denied.
        /// </summary>
        public static string ApprovalDeniedTitle {
            get {
                return ResourceManager.GetString("ApprovalDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now navigating to coach dashboard....
        /// </summary>
        public static string ApprovalPassedBody {
            get {
                return ResourceManager.GetString("ApprovalPassedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application has been approved.
        /// </summary>
        public static string ApprovalPassedTitle {
            get {
                return ResourceManager.GetString("ApprovalPassedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until you have been approved or denied.
        /// </summary>
        public static string ApprovalPendingBody {
            get {
                return ResourceManager.GetString("ApprovalPendingBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application is currently pending review.
        /// </summary>
        public static string ApprovalPendingTitle {
            get {
                return ResourceManager.GetString("ApprovalPendingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available for new clients?.
        /// </summary>
        public static string AvailabilityLabel {
            get {
                return ResourceManager.GetString("AvailabilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email..
        /// </summary>
        public static string BadEmail {
            get {
                return ResourceManager.GetString("BadEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server could not parse your request. Please report this bug..
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Application Status.
        /// </summary>
        public static string CheckApplicationStatusButton {
            get {
                return ResourceManager.GetString("CheckApplicationStatusButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string ClientCoachCriteriaCoachingGenderF {
            get {
                return ResourceManager.GetString("ClientCoachCriteriaCoachingGenderF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string ClientCoachCriteriaCoachingGenderM {
            get {
                return ResourceManager.GetString("ClientCoachCriteriaCoachingGenderM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer Not To Say.
        /// </summary>
        public static string ClientCoachCriteriaCoachingGenderPNTS {
            get {
                return ResourceManager.GetString("ClientCoachCriteriaCoachingGenderPNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workouts and Meals.
        /// </summary>
        public static string ClientCoachCriteriaCoachingTypesBoth {
            get {
                return ResourceManager.GetString("ClientCoachCriteriaCoachingTypesBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workouts.
        /// </summary>
        public static string ClientCoachCriteriaCoachingTypesMeals {
            get {
                return ResourceManager.GetString("ClientCoachCriteriaCoachingTypesMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meals.
        /// </summary>
        public static string ClientCoachCriteriaCoachingTypesWorkouts {
            get {
                return ResourceManager.GetString("ClientCoachCriteriaCoachingTypesWorkouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Calories.
        /// </summary>
        public static string CoachAddMealCaloriesLabel {
            get {
                return ResourceManager.GetString("CoachAddMealCaloriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Carbs.
        /// </summary>
        public static string CoachAddMealCarbsLabel {
            get {
                return ResourceManager.GetString("CoachAddMealCarbsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Fat.
        /// </summary>
        public static string CoachAddMealFatLabel {
            get {
                return ResourceManager.GetString("CoachAddMealFatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste an image link here.
        /// </summary>
        public static string CoachAddMealImageLabel {
            get {
                return ResourceManager.GetString("CoachAddMealImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Name.
        /// </summary>
        public static string CoachAddMealNameLabel {
            get {
                return ResourceManager.GetString("CoachAddMealNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Protein.
        /// </summary>
        public static string CoachAddMealProteinLabel {
            get {
                return ResourceManager.GetString("CoachAddMealProteinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the ingredients and cook time..
        /// </summary>
        public static string CoachAddMealRecipeLabel {
            get {
                return ResourceManager.GetString("CoachAddMealRecipeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Meal.
        /// </summary>
        public static string CoachAddMealTitle {
            get {
                return ResourceManager.GetString("CoachAddMealTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Type.
        /// </summary>
        public static string CoachAddMealTypeLabel {
            get {
                return ResourceManager.GetString("CoachAddMealTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string CoachDashboardBoard {
            get {
                return ResourceManager.GetString("CoachDashboardBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CoachDashboardClientName {
            get {
                return ResourceManager.GetString("CoachDashboardClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Progress.
        /// </summary>
        public static string CoachDashboardClientProgress {
            get {
                return ResourceManager.GetString("CoachDashboardClientProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of clients.
        /// </summary>
        public static string CoachDashboardNumOfClient {
            get {
                return ResourceManager.GetString("CoachDashboardNumOfClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search clients.
        /// </summary>
        public static string CoachDashboardSearchClients {
            get {
                return ResourceManager.GetString("CoachDashboardSearchClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string CoachDashboardTitle {
            get {
                return ResourceManager.GetString("CoachDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Clients.
        /// </summary>
        public static string CoachDashboardYourClients {
            get {
                return ResourceManager.GetString("CoachDashboardYourClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you describe yourself to clients?.
        /// </summary>
        public static string CoachDescriptionHelpText {
            get {
                return ResourceManager.GetString("CoachDescriptionHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a fun coach, always aspiring to....
        /// </summary>
        public static string CoachDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("CoachDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string CoachMealsClientPlanAdd {
            get {
                return ResourceManager.GetString("CoachMealsClientPlanAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Plan.
        /// </summary>
        public static string CoachMealsClientPlanTitle {
            get {
                return ResourceManager.GetString("CoachMealsClientPlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string CoachMealsEdit {
            get {
                return ResourceManager.GetString("CoachMealsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meals.
        /// </summary>
        public static string CoachMealsTitle {
            get {
                return ResourceManager.GetString("CoachMealsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Coach List.
        /// </summary>
        public static string CoachSelectionAvalibleListLabel {
            get {
                return ResourceManager.GetString("CoachSelectionAvalibleListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Coach was found corresponding to your search..
        /// </summary>
        public static string CoachSelectionNoAvalibleListLabel {
            get {
                return ResourceManager.GetString("CoachSelectionNoAvalibleListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  $/month.
        /// </summary>
        public static string CoachSelectionPriceLabel {
            get {
                return ResourceManager.GetString("CoachSelectionPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string CoachSelectionPriceTitleLabel {
            get {
                return ResourceManager.GetString("CoachSelectionPriceTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string CoachSelectionRequestButton {
            get {
                return ResourceManager.GetString("CoachSelectionRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Workout Plan.
        /// </summary>
        public static string CoachWorkoutClientPlanTitle {
            get {
                return ResourceManager.GetString("CoachWorkoutClientPlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workouts.
        /// </summary>
        public static string CoachWorkoutTitle {
            get {
                return ResourceManager.GetString("CoachWorkoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Account Setup.
        /// </summary>
        public static string CompleteAccountSetup {
            get {
                return ResourceManager.GetString("CompleteAccountSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Account Information.
        /// </summary>
        public static string ConfirmCoachSignUpButton {
            get {
                return ResourceManager.GetString("ConfirmCoachSignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmedPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmedPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You!\n\n If you have signed up with us previously, we will be sending you an email shortly with a link to reset your password..
        /// </summary>
        public static string ConfirmSentEmailText {
            get {
                return ResourceManager.GetString("ConfirmSentEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your coach and start your fitness journey as soon as possible!.
        /// </summary>
        public static string CriteriasTitleLabel {
            get {
                return ResourceManager.GetString("CriteriasTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Weight.
        /// </summary>
        public static string CurrentWeightLabel {
            get {
                return ResourceManager.GetString("CurrentWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match!.
        /// </summary>
        public static string DifferentPasswords {
            get {
                return ResourceManager.GetString("DifferentPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string DontHaveAccountLabel {
            get {
                return ResourceManager.GetString("DontHaveAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Meal.
        /// </summary>
        public static string EditMealPageTitle {
            get {
                return ResourceManager.GetString("EditMealPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Updated..
        /// </summary>
        public static string EditMealSaved {
            get {
                return ResourceManager.GetString("EditMealSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout Not Found. Please try again.
        /// </summary>
        public static string EditWorkoutNotFoundMessage {
            get {
                return ResourceManager.GetString("EditWorkoutNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Workout.
        /// </summary>
        public static string EditWorkoutPageTitle {
            get {
                return ResourceManager.GetString("EditWorkoutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout Updated..
        /// </summary>
        public static string EditWorkoutSaved {
            get {
                return ResourceManager.GetString("EditWorkoutSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string FemaleGender {
            get {
                return ResourceManager.GetString("FemaleGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name:.
        /// </summary>
        public static string FileNameTextStart {
            get {
                return ResourceManager.GetString("FileNameTextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a gender, if you have a prefered coach gender.
        /// </summary>
        public static string FindACoachByCriteriaGenderLabel {
            get {
                return ResourceManager.GetString("FindACoachByCriteriaGenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us find one for you!.
        /// </summary>
        public static string FindACoachByCriteriaLabel {
            get {
                return ResourceManager.GetString("FindACoachByCriteriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coach Name.
        /// </summary>
        public static string FindACoachByCriteriaNameLabel {
            get {
                return ResourceManager.GetString("FindACoachByCriteriaNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - OR -.
        /// </summary>
        public static string FindACoachByCriteriaOrLabel {
            get {
                return ResourceManager.GetString("FindACoachByCriteriaOrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string FindACoachByCriteriaSearchButton {
            get {
                return ResourceManager.GetString("FindACoachByCriteriaSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the coaching type that best fits you.
        /// </summary>
        public static string FindACoachByCriteriaTypeLabel {
            get {
                return ResourceManager.GetString("FindACoachByCriteriaTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a coach by name.
        /// </summary>
        public static string FindACoachByNameLabel {
            get {
                return ResourceManager.GetString("FindACoachByNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password ?.
        /// </summary>
        public static string ForgotPasswordLabel {
            get {
                return ResourceManager.GetString("ForgotPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email associated with your account..
        /// </summary>
        public static string ForgotPasswordPrompt {
            get {
                return ResourceManager.GetString("ForgotPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullNamePlaceholder {
            get {
                return ResourceManager.GetString("FullNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string GenderLabel {
            get {
                return ResourceManager.GetString("GenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your password was incorrect. Please check your password and try again..
        /// </summary>
        public static string IncorrectLoginText {
            get {
                return ResourceManager.GetString("IncorrectLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email that you have entered is not valid..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is verified.
        /// </summary>
        public static string IsVerifiedLabel {
            get {
                return ResourceManager.GetString("IsVerifiedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached exceeded the maximum login attempts. Please try again later..
        /// </summary>
        public static string LoginAttempsExceededText {
            get {
                return ResourceManager.GetString("LoginAttempsExceededText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string MaleGender {
            get {
                return ResourceManager.GetString("MaleGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer meal coaching.
        /// </summary>
        public static string MealServiceLabel {
            get {
                return ResourceManager.GetString("MealServiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload your certification..
        /// </summary>
        public static string MissingCertificationError {
            get {
                return ResourceManager.GetString("MissingCertificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all required fields..
        /// </summary>
        public static string MissingInputs {
            get {
                return ResourceManager.GetString("MissingInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherGender {
            get {
                return ResourceManager.GetString("OtherGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one digit.\n.
        /// </summary>
        public static string PasswordRequirementDigit {
            get {
                return ResourceManager.GetString("PasswordRequirementDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be 8 characters long.\n.
        /// </summary>
        public static string PasswordRequirementsLength {
            get {
                return ResourceManager.GetString("PasswordRequirementsLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase character.\n.
        /// </summary>
        public static string PasswordRequirementUppercase {
            get {
                return ResourceManager.GetString("PasswordRequirementUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one symbol..
        /// </summary>
        public static string PasswordRequirmentSymbol {
            get {
                return ResourceManager.GetString("PasswordRequirmentSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to provide coaching for?.
        /// </summary>
        public static string PlanOffersHelpText {
            get {
                return ResourceManager.GetString("PlanOffersHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a gender.
        /// </summary>
        public static string PleaseSelectAGender {
            get {
                return ResourceManager.GetString("PleaseSelectAGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your certification.
        /// </summary>
        public static string PleaseSelectCertification {
            get {
                return ResourceManager.GetString("PleaseSelectCertification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid pricing..
        /// </summary>
        public static string PricingError {
            get {
                return ResourceManager.GetString("PricingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Profile.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file type. Please select a PDF..
        /// </summary>
        public static string SelectPDFError {
            get {
                return ResourceManager.GetString("SelectPDFError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUpLabel {
            get {
                return ResourceManager.GetString("SignUpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify your gender..
        /// </summary>
        public static string SpecifyGenderError {
            get {
                return ResourceManager.GetString("SpecifyGenderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Weight.
        /// </summary>
        public static string StartWeightLabel {
            get {
                return ResourceManager.GetString("StartWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unknown issue communicating with the server. Please try again later..
        /// </summary>
        public static string UnknownErrorText {
            get {
                return ResourceManager.GetString("UnknownErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Certification (PDF).
        /// </summary>
        public static string UploadCertificationButton {
            get {
                return ResourceManager.GetString("UploadCertificationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured on the server. Please try saving again..
        /// </summary>
        public static string ViewModelErrorMessage {
            get {
                return ResourceManager.GetString("ViewModelErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ViewModelErrorTitle {
            get {
                return ResourceManager.GetString("ViewModelErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill ALL of the fields..
        /// </summary>
        public static string ViewModelFieldIssueMessage {
            get {
                return ResourceManager.GetString("ViewModelFieldIssueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Error.
        /// </summary>
        public static string ViewModelFieldIssueTitle {
            get {
                return ResourceManager.GetString("ViewModelFieldIssueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile saved..
        /// </summary>
        public static string ViewModelProfileSuccessMessage {
            get {
                return ResourceManager.GetString("ViewModelProfileSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string ViewModelSuccessTitle {
            get {
                return ResourceManager.GetString("ViewModelSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer workout coaching.
        /// </summary>
        public static string WorkoutServiceLabel {
            get {
                return ResourceManager.GetString("WorkoutServiceLabel", resourceCulture);
            }
        }
    }
}
